import type { Metadata } from "next";
import { Space_Grotesk } from "next/font/google";
// import localFont from "next/font/local";
import "@/app/globals.css";
import Navbar from "@/app/components/Navbar";
import Footer from "@/app/components/Footer";
import Notice from "@/app/components/Notice";

// const geistSans = localFont({
//   src: "./fonts/GeistVF.woff",
//   variable: "--font-geist-sans",
//   weight: "100 900",
// });
// const geistMono = localFont({
//   src: "./fonts/GeistMonoVF.woff",
//   variable: "--font-geist-mono",
//   weight: "100 900",
// });

const spaceGrotesk = Space_Grotesk({
  subsets: ["latin"],
  weight: ["400", "500", "700"],
});

export const metadata: Metadata = {
  title: "Imaginem",
  description: "Generated by create next app",
};

export default function ProtectedLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <div className={spaceGrotesk.className}>
      <div className="sticky top-0 z-50 w-full">
        <Navbar />
        <Notice />
      </div>
      {/* <br /> <br /> */}
      {children}
      <br />
      <br />
      <br /> <br />
      {/* <Footer /> */}
    </div>
  );
}
