import type { Metadata } from "next";
import { Space_Grotesk } from "next/font/google";
// import localFont from "next/font/local";
import "@/app/globals.css";
import Navbar from "@/app/components/Navbar";
import Footer from "@/app/components/Footer";
import Notice from "@/app/components/Notice";
import { createClient } from "@/utils/supabase/server"; // Import server client
import { redirect } from "next/navigation";
import { activeUser } from "../_lib/data";

const spaceGrotesk = Space_Grotesk({
  subsets: ["latin"],
  weight: ["400", "500", "700"],
});

export const metadata: Metadata = {
  title: "Imaginem",
  description: "Generated by create next app",
};

export default async function ProtectedLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const user = await activeUser();

  const navData = {
    firstName: user?.firstName ?? "Guest",
    lastName: user?.lastName ?? "User",
    role: user?.role ?? "guest",
  };

  return (
    <div className={spaceGrotesk.className}>
      <div className="sticky top-0 z-50 w-full">
        <Navbar userData={navData} />
        <Notice />
      </div>
      {/* <br /> <br /> */}
      {children}
      <br />
      <br />
      <br /> <br />
      {/* <Footer /> */}
    </div>
  );
}
